


package VeriYapilari;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
  Amine Ceyda ABANİK
 * 1721221024
 * VERİ YAPILARI ÖDEV 1
 */
public class Main extends javax.swing.JFrame {

    static DefaultListModel<String> listModel = new DefaultListModel<>();
    static DefaultListModel<String> listModel2 = new DefaultListModel<>();
    static DefaultListModel<String> listModel3 = new DefaultListModel<>();
    static DefaultListModel<String> listModel4 = new DefaultListModel<>();
    static Queue kuyruk1 = new Queue(150);

    /**
     * Creates new form SwingMain
     */
    public Main() {
        this.setTitle("AMİNE CEYDA ABANİK");
        initComponents();
        MusteriGoster.setModel(listModel);
        AnlıkIslemList.setModel(listModel2);
        MusteriOnceligiList.setModel(listModel3);
        vezneMusteriGecmisiList.setModel(listModel4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dosyaOkumaButonu = new javax.swing.JButton();
        vezneCalısıyor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bankaKapandı = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adSoyadgiris = new javax.swing.JTextField();
        Oncelikgiris = new javax.swing.JTextField();
        SureGiris = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        musteriEkleButon = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MusteriGoster = new javax.swing.JList<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        vezneMusteriGecmisiList = new javax.swing.JList<String>();
        jScrollPane3 = new javax.swing.JScrollPane();
        MusteriOnceligiList = new javax.swing.JList<String>();
        jScrollPane4 = new javax.swing.JScrollPane();
        AnlıkIslemList = new javax.swing.JList<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        dosyaOkumaButonu.setBackground(new java.awt.Color(204, 0, 0));
        dosyaOkumaButonu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dosyaOkumaButonu.setForeground(new java.awt.Color(255, 255, 255));
        dosyaOkumaButonu.setText("Dosya Oku");
        dosyaOkumaButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaOkumaButonuActionPerformed(evt);
            }
        });

        vezneCalısıyor.setBackground(new java.awt.Color(255, 0, 0));
        vezneCalısıyor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        vezneCalısıyor.setForeground(new java.awt.Color(255, 255, 255));
        vezneCalısıyor.setText("Vezne Çalışır");
        vezneCalısıyor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vezneCalısıyorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Öncelkli Kuyruk Yapısı");

        bankaKapandı.setBackground(new java.awt.Color(255, 0, 0));
        bankaKapandı.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bankaKapandı.setForeground(new java.awt.Color(255, 255, 255));
        bankaKapandı.setText("Banka Kapalı");
        bankaKapandı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankaKapandıActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("İşlem Gören Müşteri Bilgileri");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Müsteri Ekle");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Ad Soyad:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Öncelik:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Süre:");

        adSoyadgiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adSoyadgirisActionPerformed(evt);
            }
        });

        Oncelikgiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OncelikgirisActionPerformed(evt);
            }
        });

        SureGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SureGirisActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Vezne Müşteri Gecmisi");

        musteriEkleButon.setBackground(new java.awt.Color(255, 0, 0));
        musteriEkleButon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        musteriEkleButon.setForeground(new java.awt.Color(255, 255, 255));
        musteriEkleButon.setText("Ekle");
        musteriEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriEkleButonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Müşterilerin Önceliğine Göre İstatistik");

        MusteriGoster.setBackground(new java.awt.Color(255, 102, 102));
        MusteriGoster.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(MusteriGoster);

        vezneMusteriGecmisiList.setBackground(new java.awt.Color(255, 102, 102));
        vezneMusteriGecmisiList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(vezneMusteriGecmisiList);

        MusteriOnceligiList.setBackground(new java.awt.Color(255, 102, 102));
        MusteriOnceligiList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(MusteriOnceligiList);

        AnlıkIslemList.setBackground(new java.awt.Color(255, 102, 102));
        AnlıkIslemList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(AnlıkIslemList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(dosyaOkumaButonu)
                                                .addGap(31, 31, 31)
                                                .addComponent(vezneCalısıyor)))
                                        .addGap(77, 77, 77)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(76, 76, 76)
                                        .addComponent(bankaKapandı))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(SureGiris, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Oncelikgiris, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(adSoyadgiris, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(musteriEkleButon)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(111, 111, 111)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(249, 249, 249)
                                                .addComponent(jLabel7))))))
                            .addComponent(jLabel8))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dosyaOkumaButonu)
                            .addComponent(vezneCalısıyor)
                            .addComponent(bankaKapandı))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(adSoyadgiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Oncelikgiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SureGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(musteriEkleButon))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 976, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dosyaOkumaButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaOkumaButonuActionPerformed

        File file = new File("musteri.txt");
        Scanner scanner;

        try {
            scanner = new Scanner(file);

            while (scanner.hasNext()) {

                String[] line = scanner.nextLine().split("#");

                Musteri m1 = new Musteri(line[0], Integer.valueOf(line[1]), Long.valueOf(line[2]));
                LinkedList.liste.AddFirst(m1); 
                LinkedList.listetemp.AddFirst(m1);
            }
            int length = LinkedList.liste.getSize();
            int lengthtemp = LinkedList.liste.getSize();

            kuyruk1.printQueque();
            
            for (int i = 0; i < length; i++) {
                kuyruk1.insert(LinkedList.liste.head.data);
                LinkedList.liste.head = LinkedList.liste.head.nextNode;

            }

            for (int i = 0; i < lengthtemp; i++) {
                listModel.addElement(kuyruk1.getQueque((lengthtemp - 1) - i));
            }

            scanner.close();
            listModel.addElement("Okuma tamamlandı");
        } catch (FileNotFoundException e) {
         
            e.printStackTrace();
        }
        

    }//GEN-LAST:event_dosyaOkumaButonuActionPerformed
    public static void wait(int ms) {
        try {
            Thread.sleep(ms);
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
        }
    }

    public static void islemTamamlanan(int counter) {
        listModel4.addElement( "oncelik: "+kuyruk1.getData(counter).oncelik +"isim: " +kuyruk1.getData(counter).isim + " süre: " + kuyruk1.getData(counter).islemSuresi);
        listModel4.addElement("*********************** \n" );
    }
    public static void dosyaYaz() {
        
        File file = new File("gunlukIslem.txt");
        for (int i = 0; i < kuyruk1.getCount(); i++) {
            String str = kuyruk1.getQueque(i);
            try (BufferedWriter br = new BufferedWriter(new FileWriter(file))) {
                br.write(str+"\n");
                br.newLine();

            } catch (IOException e) {
                System.out.println("Unable to read file " + file.toString());
            }
        }

    }
    private void vezneCalısıyorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vezneCalısıyorActionPerformed
      
        int toplam = 0;
        for (int i = (kuyruk1.getCount() - 1); i >= 0; i--) {
           
            System.out.println(kuyruk1.getData(i).isim + " şu anda işlem yapıyor");
            listModel2.addElement(kuyruk1.getData(i).isim);
            wait((int) kuyruk1.getData(i).islemSuresi);
            islemTamamlanan(i);
            dosyaYaz();
            toplam += (int) kuyruk1.getData(i).islemSuresi;
        }
        JOptionPane.showMessageDialog(null, " İşlemler Tamamlandı " + toplam, " süre içerisinde", JOptionPane.INFORMATION_MESSAGE);

        int toplam0 = 0;
        int toplam1 = 0;
        int toplam2 = 0;
        int toplam3 = 0;
        for (int i = 0; i < kuyruk1.getCount(); i++) {
            switch (kuyruk1.getData(i).oncelik) {
                case 0:
                    toplam0 += (int) kuyruk1.getData(i).islemSuresi;
                    break;
                case 1:
                    toplam1 += (int) kuyruk1.getData(i).islemSuresi;
                    break;
                case 2:
                    toplam2 += (int) kuyruk1.getData(i).islemSuresi;
                    break;
                case 3:
                    toplam3 += (int) kuyruk1.getData(i).islemSuresi;
                    break;
            }
        }
        listModel3.addElement("0.işlem önceliği için geçen süre:" + String.valueOf(toplam0) + "ms");
        listModel3.addElement("1.işlem önceliği için geçen süre:" + String.valueOf(toplam1) + "ms");
        listModel3.addElement("2.işlem önceliği için geçen süre:" + String.valueOf(toplam2) + "ms");
        listModel3.addElement("3.işlem önceliği için geçen süre:" + String.valueOf(toplam3) + "ms");
        listModel3.addElement("Toplam geçen süre:" + String.valueOf(toplam0 + toplam1 + toplam2 + toplam3) + "ms");
        listModel3.addElement("-------------------------------------------------------");


    }//GEN-LAST:event_vezneCalısıyorActionPerformed

    private void bankaKapandıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankaKapandıActionPerformed
        JOptionPane.showMessageDialog(null,"" ,"İyi Günler ", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_bankaKapandıActionPerformed

    private void adSoyadgirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adSoyadgirisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adSoyadgirisActionPerformed

    private void OncelikgirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OncelikgirisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OncelikgirisActionPerformed

    private void SureGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SureGirisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SureGirisActionPerformed

    private void musteriEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriEkleButonActionPerformed
        String isim = adSoyadgiris.getText();
        int öncelik = Integer.parseInt(Oncelikgiris.getText());
        long sure = Long.parseLong(SureGiris.getText());
        Musteri m1 = new Musteri(isim, öncelik, sure);
        LinkedList.liste.AddFirst(m1);
        System.out.println(m1.isim + " Listeye eklendiniz Hoşgeldiniz...");
    }//GEN-LAST:event_musteriEkleButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> AnlıkIslemList;
    private javax.swing.JList<String> MusteriGoster;
    private javax.swing.JList<String> MusteriOnceligiList;
    private javax.swing.JTextField Oncelikgiris;
    private javax.swing.JTextField SureGiris;
    private javax.swing.JTextField adSoyadgiris;
    private javax.swing.JButton bankaKapandı;
    private javax.swing.JButton dosyaOkumaButonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton musteriEkleButon;
    private javax.swing.JButton vezneCalısıyor;
    private javax.swing.JList<String> vezneMusteriGecmisiList;
    // End of variables declaration//GEN-END:variables
}
